// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejliszzbuxgihworwxgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqbGlzenpidXhnaWh3b3J3eGdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NTUyNzUsImV4cCI6MjA2OTAzMTI3NX0.Pz0og61Wih6K0EITtojJh3rhJeA9Z2yQgwhIlrmCHqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});